### PR TITLE
Add support for passing the progress values to raop callbacks.

### PR DESCRIPTION
**Pull request by Memphiz**
This is the rebased version of your progress branch - ready to merge into master...

### CODE REVIEW

**Comment by juhovh** [comment]
Merged into master, the API might or might not change in the future, but that shouldn't be a huge issue.

**Comment by Memphiz** [comment]
As an api change suggestion - the dacp id should be passed via the init callback really because its something that won't change during the whole stream session. ;)

**Comment by juhovh** [comment]
Yeah, I've thought about that. On the other habd it is sent on every RTSP request so in theory it might change, also it is not useful for all users so keeping it in a separate callback that can be just left unimplemented if not needed might be nice as well. Do you need to do some hacks if it's sent after init?

**Comment by Memphiz** [comment]
nah its fine ;)

**Pull request merged**
